/*
 * Calculator
 * Arithemtics over HTTP!\"
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SubApi
 */
@Ignore
public class SubApiTest {

    private final SubApi api = new SubApi();

    
    /**
     * Add two numbers
     *
     * Subtracts two numbers send as parameters.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void subTest() throws ApiException {
        Double a = null;
        Double b = null;
        String response = api.sub(a, b);

        // TODO: test validations
    }
    
}
